# SITE CONFIGURATION
title: Katja Vock # your site title
author: KatjaVock # You :P
description: > # Meta description of Homepage
 Motivated and curious graduated computer and information science student with specialization in human computer interaction and data visualization with a history of working within finance as well as e-commerce.
 Having an analytical and pragmatic mindset with a wide focus on user experience and aspiring to gather work experience.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://katjavock.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Katja Vock
  links:
    #- https://twitter.com/BenBalter
    #- https://www.facebook.com/ben.balter
    #- https://ch.linkedin.com/in/katja-vock-7b657366
    #- https://plus.google.com/+BenBalter
    #- https://github.com/benbalter
    #- https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
Currently I’m a UX Designer Intern at Thomson Reuters and aspiring to gather work experience.

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: katja.vock@gmail.com # email for form submission

# twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
# github_username:  janczizikow # replace with your_github_username or comment to remove link from footer
# instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: katjavock # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
